name: End to End Tests

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
      
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 18

            - name: Install Tests dependencies
              run: npm install
      
            - name: Clone Project repository
              run: git clone https://github.com/cypress-io/cypress-realworld-app

            - name: Install Yarn
              run: cd cypress-realworld-app && npm install -G yarn --force

            - name: Install Project dependencies
              run: npm install --force

            - name: Run Project
              run: yarn dev &
      
            - name: Run Tests
              run: cd ../ && cd realworld-cypress-test && npm run cy:run